package embed

import "text/template"

const text = `// Code generated by go generate; DO NOT EDIT.
package template

import html "html/template"
import "net/http"

type Template struct {
	*html.Template
}

func (t *Template) Render(w http.ResponseWriter, d interface{}, c ...int) error {
	w.Header().Set("Content-Type", "text/html")

	if len(c) > 0 {
		w.WriteHeader(c[0])
	}

	if err := t.Execute(w, d); err != nil {
		return err
	}

	return nil
}

{{ $templates := . }}

{{ range $t := $templates }}
	var {{ $t.Title }}Byte = []byte{ {{ $t.Data }} }
	var {{ $t.Name }}String = string({{ $t.Title }}Byte)
	{{- if $t.Generate }}
	var {{ $t.Title }} = &Template{html.Must(html.New("{{ $t.Name }}").Parse({{ $t.Name }}String))}
	{{- end }}
{{ end }}

func init() {
	{{- range $t := $templates }}
		{{- if $t.Generate }}
			{{- range $t2 := $templates }}
				{{- if not $t2.Generate }}
					html.Must({{ $t.Title }}.Parse({{ $t2.Name }}String))
				{{- end }}
			{{- end }}
		{{- end }}
	{{- end }}
}
`

var tmpl = template.Must(template.New("").Parse(text))
